import type { ReactNode } from 'react';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Compass, Crosshair, Minus, Plus, RotateCcw, ScanLine, SignalZero } from 'lucide-react';
import { chapters, features, scenarios, stations } from '../data/mission';
import type { SceneControls } from '../data/mission';
import NavigationMap from './NavigationMap';
import CommandReveal from './CommandReveal';

function Section({ index, className = '', children }: { index: number; className?: string; children: ReactNode }) {
  return <section id={chapters[index].id} data-chapter={index} className={`story-section ${className}`} aria-label={chapters[index].title}>{children}</section>;
}
function Eyebrow({ index }: { index: number }) { return <p className="eyebrow section-eyebrow" data-reveal><span className="tiny-cross">+</span>{chapters[index].tag}</p>; }
function Metric({ label, value, unit, className = '' }: { label: string; value: string; unit?: string; className?: string }) { return <div className={`metric ${className}`}><span className="eyebrow">{label}</span><strong>{value}<small>{unit}</small></strong></div>; }
function FeatureVisual({ index }: { index: number }) {
  return <svg className={`feature-visual feature-${index}`} viewBox="0 0 200 85" aria-hidden="true"><path d="M0 70h200M25 0v85M75 0v85M125 0v85M175 0v85" className="feature-grid" />{index % 3 === 0 ? <><path d="m70 62 20-43 14 16 13-9 24 36Z" className="feature-ice" /><ellipse cx="105" cy="53" rx="60" ry="20" className="feature-ring" /><path d="M20 38h165" className="feature-scan" /></> : index % 3 === 1 ? <><path d="M10 66Q52 80 80 40T190 12" className="feature-path" /><path d="M10 66Q65 45 85 57T190 32" className="feature-path secondary" /><circle r="3" className="feature-traveler"><animateMotion dur="5s" repeatCount="indefinite" path="M10 66Q52 80 80 40T190 12" /></circle></> : <>{[0, 1, 2, 3].map(i => <path key={i} d={`M0 ${20 + i * 14}q30-18 60 0t60 0t60 0t60 0`} className="feature-wave" style={{ animationDelay: `${i * -.5}s` }} />)}</>}</svg>;
}

type Props = { go: (id: string) => void; command: () => void; controls: SceneControls; setControl: <K extends keyof SceneControls>(key: K, value: SceneControls[K]) => void; station: string; setStation: (id: string) => void; scenario: string; setScenario: (id: string) => void; running: boolean; progress: number; run: () => void; reduced: boolean };

export default function Story({ go, command, controls, setControl, station, setStation, scenario, setScenario, running, progress, run, reduced }: Props) {
  const selectedStation = stations.find(item => item.id === station) ?? stations[0];
  const selectedScenario = scenarios.find(item => item.id === scenario) ?? scenarios[0];
  return <main className="story">
    <Section index={0} className="hero-section">
      <motion.div className="hero-copy" initial={{ opacity: 0, y: reduced ? 0 : 32 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 1.5, delay: 1.7 }}>
        <p className="eyebrow hero-eyebrow"><span className="status-dot" /> INTELLIGENCE AT THE EDGE OF THE WORLD</p>
        <h1>PREDICT<br /><span className="ice-word">THE ICE<span className="period">.</span></span></h1>
        <h2>Navigate with intelligence.</h2>
        <p className="hero-description">An ocean of uncertainty.<br />One intelligent way forward.</p>
        <button className="primary-button" onClick={() => go('ice')}>Explore the mission<ArrowDown size={16} /></button>
        <div className="hero-caption"><span>AI-ENABLED ANTARCTIC<br />NAVIGATION SYSTEM</span><span className="caption-rule" /><span>DESIGNED FOR<br />THE UNPREDICTABLE</span></div>
      </motion.div>
      <div className="hero-object-tag"><span className="tag-line" /><span className="eyebrow">IBG-001 / TABULAR</span><small>94% DETECTION CONFIDENCE</small></div>
      <div className="hero-location"><span className="eyebrow">EXPEDITION 001</span><strong>ANTARCTICA</strong><span className="mono">−11°C &nbsp; / &nbsp; WIND 22 KT</span></div>
      <span className="hero-watermark" aria-hidden="true">69°S</span>
    </Section>

    <Section index={1} className="align-right"><div className="chapter-copy"><Eyebrow index={1} /><h2 data-reveal>The ice is<br /><em>never still.</em></h2><p data-reveal>Entire landscapes drift while the world sleeps. Understanding where an iceberg is? That is only the beginning.</p><div className="data-pair" data-reveal><Metric label="TRACKED OBJECTS" value="12" /><Metric label="AVERAGE DRIFT" value="0.8" unit="KT" /></div></div><div className="bottom-annotation"><span className="status-dot" /> CONTINUOUS MOTION / CONTINUOUS OBSERVATION</div></Section>

    <Section index={2}><div className="chapter-copy narrow"><Eyebrow index={2} /><h2 data-reveal>A mountain.<br /><em>A signal.</em></h2><p data-reveal>Satellite observations become object intelligence. Detection, classification, and motion. Connected.</p><div className="scan-readout" data-reveal><span className="eyebrow"><ScanLine size={13} /> OBJECT DETECTED</span><h3>IBG-001</h3><div className="readout-row"><span>CLASSIFICATION</span><b>TABULAR</b></div><div className="readout-row"><span>CONFIDENCE</span><b>94.0%</b></div><div className="confidence-bar"><i /></div><span className="mono muted">ILLUSTRATIVE SATELLITE OBSERVATION</span></div></div></Section>

    <Section index={3} className="align-right"><div className="chapter-copy"><Eyebrow index={3} /><h2 data-reveal>A higher<br /><em>perspective.</em></h2><p data-reveal>Above the clouds. Beyond the horizon. An uninterrupted chain of intelligence, from orbit to ocean.</p><div className="data-pipeline" data-reveal>{['SATELLITE DATA', 'OBJECT DETECTION', 'ICEBERG CLASSIFICATION', 'TRAJECTORY ANALYSIS'].map((label, i) => <div key={label} style={{ animationDelay: `${i * .3}s` }}><span>0{i + 1}</span>{label}<Check size={13} /></div>)}</div></div></Section>

    <Section index={4}><div className="chapter-copy wide"><Eyebrow index={4} /><h2 data-reveal>We don’t just<br />see the ice.<br /><em className="accent">We predict it.</em></h2><p data-reveal>Historical movement. Ocean currents. Wind.<br />A window into the next 24 hours.</p><div className="trajectory-legend" data-reveal><span><i className="history" />HISTORY</span><span><i className="current" />NOW</span><span><i className="forecast" />PREDICTED</span></div><div className="time-horizons" data-reveal><span>+6 HOURS</span><span>+12 HOURS</span><span>+24 HOURS</span></div><p className="micro" data-reveal>The translucent corridor represents increasing forecast uncertainty.</p></div></Section>

    <Section index={5} className="danger-section align-right"><div className="chapter-copy"><Eyebrow index={5} /><div className="alert-tag" data-reveal><span className="status-dot" /> ROUTE CONFLICT DETECTED</div><h2 data-reveal>Two paths.<br /><em>One collision.</em></h2><div className="risk-number" data-reveal>78<span>%</span></div><p className="eyebrow" data-reveal>ILLUSTRATIVE COLLISION PROBABILITY</p><div className="data-pair" data-reveal><Metric label="CLOSEST APPROACH" value="4.2" unit="NM" /><Metric label="TIME TO APPROACH" value="3h 24m" /></div></div></Section>

    <Section index={6}><div className="chapter-copy"><Eyebrow index={6} /><h2 data-reveal>A thousand variables.<br /><em>One clear decision.</em></h2><p data-reveal>NAVDRISHTI is analyzing the environment.</p><div className="analysis-list" data-reveal>{['Iceberg velocity', 'Sea ice concentration', 'Weather conditions', 'Ocean currents', 'Alternative passages'].map((text, i) => <div key={text} style={{ '--order': i } as React.CSSProperties}><span className="mono">0{i + 1}</span><span>{text}</span><Check size={15} /></div>)}</div></div><div className="bottom-annotation mono">EVALUATE → COMPARE → OPTIMIZE</div></Section>

    <Section index={7} className="align-right safe-section"><div className="chapter-copy"><Eyebrow index={7} /><div className="safe-tag" data-reveal><span className="status-dot" /> OPTIMAL PASSAGE IDENTIFIED</div><h2 data-reveal>There is<br /><em>another way.</em></h2><div className="risk-reduction" data-reveal><span>78<small>%</small></span><ArrowRight strokeWidth={1} /><strong>14<small>%</small></strong></div><p className="eyebrow" data-reveal>COLLISION RISK / BEFORE → AFTER</p><div className="data-pair" data-reveal><Metric label="FUEL SAVING" value="18" unit="%" /><Metric label="ROUTE SAFETY" value="92" unit="%" /></div><p className="decision-text" data-reveal><Check size={14} /> Avoids predicted drift. Lower sea ice.<br />Better weather. Less fuel. More certainty.</p></div></Section>

    <Section index={8} className="center-section escape-section"><div className="chapter-copy wide"><Eyebrow index={8} /><h2 data-reveal>Navigation.<br /><em>Reimagined.</em></h2><p data-reveal>Intelligence before impact.</p></div><span className="bottom-annotation"><span className="status-dot" /> COURSE CORRECTED / SAFE PASSAGE</span></Section>

    <Section index={9}><div className="chapter-copy twin-copy"><Eyebrow index={9} /><h2 data-reveal>The whole<br /><em>living system.</em></h2><p data-reveal>A digital twin of the Antarctic environment. Every vessel, iceberg, current, and route in one connected view.</p><p className="micro" data-reveal>Illustrative terrain and station placement.</p><div className="twin-controls" data-reveal><button aria-pressed={controls.orbit} onClick={() => setControl('orbit', !controls.orbit)}><RotateCcw size={15} />Rotate</button><button aria-label="Zoom in" onClick={() => setControl('zoom', Math.max(.55, controls.zoom - .15))}><Plus size={15} /></button><button aria-label="Zoom out" onClick={() => setControl('zoom', Math.min(1.5, controls.zoom + .15))}><Minus size={15} /></button><button aria-pressed={controls.focus} onClick={() => setControl('focus', !controls.focus)}><Crosshair size={15} />Focus vessel</button>{(['icebergs', 'routes', 'seaIce'] as const).map(key => <button key={key} aria-pressed={controls[key]} onClick={() => setControl(key, !controls[key])}><span className="toggle-indicator" />{key === 'seaIce' ? 'Sea ice' : key[0].toUpperCase() + key.slice(1)}</button>)}</div><button className="text-button" onClick={command} data-reveal>Open command center<ArrowUpRight size={18} /></button></div></Section>

    <Section index={10} className="capability-section"><div className="capability-heading"><Eyebrow index={10} /><h2 data-reveal>Many signals.<br /><em>One intelligence.</em></h2><p data-reveal>Built for the complexity of the real world.</p></div><div className="feature-grid-layout">{features.map(([number, title, description, link], i) => <button className="feature-card" key={number} onClick={() => go(link)} data-reveal><div className="feature-top"><span className="mono">{number} /</span><ArrowUpRight size={16} /></div><FeatureVisual index={i} /><h3>{title}</h3><p>{description}</p></button>)}<button className="feature-card command-feature" onClick={command} data-reveal><Compass size={30} strokeWidth={1} /><h3>Your command.<br />Our intelligence.</h3><span className="text-button">Enter command center<ArrowUpRight size={17} /></span></button></div><CommandReveal open={command} /></Section>

    <Section index={11} className="align-right"><div className="chapter-copy"><Eyebrow index={11} /><h2 data-reveal>For those who<br /><em>go further.</em></h2><p data-reveal>Designed with Antarctic research operations in mind. A safer journey to the places that expand our understanding.</p><div className="station-tabs" data-reveal role="group" aria-label="Research station">{stations.map(item => <button key={item.id} className={station === item.id ? 'selected' : ''} onClick={() => setStation(item.id)}>{item.name.toUpperCase()}<ArrowUpRight size={13} /></button>)}</div><div className="station-info" data-reveal><p className="eyebrow">{selectedStation.coords}</p><h3>{selectedStation.name} Station</h3><div className="data-pair"><Metric label="DISTANCE" value={selectedStation.distance} unit="NM" /><Metric label="ETA" value={selectedStation.eta} /></div><div className="station-weather"><span>{selectedStation.temp}°C</span><span>WIND {selectedStation.wind} KT</span><span className="accent">LOW APPROACH RISK</span></div></div><p className="prototype-note" data-reveal>Prototype for research operations. Simulated readings; no official deployment or government affiliation.</p></div></Section>

    <Section index={12} className="simulation-section"><div className="simulation-heading"><Eyebrow index={12} /><h2 data-reveal>What <em>if?</em></h2><p data-reveal>Change the conditions. Challenge the intelligence.</p></div><div className="simulator" data-reveal><div className="simulation-sidebar"><p className="eyebrow">ANTARCTIC NAVIGATION SIMULATOR</p><div className="scenario-options" role="group" aria-label="Simulation scenario">{scenarios.map((item, i) => <button key={item.id} onClick={() => setScenario(item.id)} aria-pressed={scenario === item.id}><span>0{i + 1}</span>{item.title}{item.id === 'offline' ? <SignalZero size={14} /> : <ArrowUpRight size={14} />}</button>)}</div><p className="scenario-description">{selectedScenario.detail}</p><button className="primary-button" onClick={run} disabled={running}>{running ? 'Calculating passage…' : progress >= 1 ? 'Replay simulation' : 'Run simulation'}{progress >= 1 ? <RotateCcw size={16} /> : <ArrowRight size={16} />}</button><p className="prototype-note">Deterministic demonstration. Scores are simulated, not predictions from a trained model.</p></div><div className="simulation-visual"><div className="simulation-status"><span className="eyebrow"><span className={`status-dot ${running ? 'pulsing' : ''}`} />{running ? 'SIMULATION IN PROGRESS' : progress >= 1 ? 'MISSION COMPLETE' : 'AWAITING SCENARIO'}</span><span className="mono">{String(Math.round(progress * 100)).padStart(2, '0')}%</span></div><NavigationMap progress={Math.max(.03, progress)} storm={scenario === 'storm'} alternate={scenario === 'storm'} /><div className="simulation-progress"><i style={{ width: `${progress * 100}%` }} /></div><div className="simulation-results" aria-live="polite"><Metric label="SAFETY" value={progress >= 1 ? String(selectedScenario.safety) : '—'} unit="%" /><Metric label="FUEL EFFICIENCY" value={progress >= 1 ? String(selectedScenario.fuel) : '—'} unit="%" /><Metric label="NAVIGATION SCORE" value={progress >= 1 ? String(selectedScenario.score) : '—'} unit="/100" /></div></div></div></Section>

    <Section index={13} className="center-section final-section"><div className="chapter-copy wide"><Eyebrow index={13} /><p className="final-preface" data-reveal>The ice will move.</p><h2 data-reveal>NAVDRISHTI<br /><em>will be ready.</em></h2><button className="primary-button" onClick={command} data-reveal>Explore NAVDRISHTI<ArrowUpRight size={17} /></button><p className="final-credit" data-reveal>BUILT FOR THE UNKNOWN. GUIDED BY INTELLIGENCE.<br /><span>POLARIS / SIH CONCEPT PROTOTYPE</span></p></div></Section>
  </main>;
}
